theme: jekyll-theme-dinky
title: 50 sfumature
description: >-
  Learn how to create a site or blog from your GitHub repositories with GitHub
  Pages.
tags:
  - GitHub
  - GitHub Pages
preferences:
  - type: dropdown
    name: language
    label: Language
    description: Choose your preferred language.
    options:
      - label: English
        value: en
      - label: Español
        value: es
